# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec — Windows EXE  (v2.0)
# Chạy: pyinstaller O2O_Inspection.spec --clean --noconfirm
#   hoặc dùng flet pack (xem build-release.yml)

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('checklist.json', '.'),
    ],
    hiddenimports=[
        # ── API key (generated by build_inject_key.py) ──
        '_embedded_key',
        # ── Windows WMI ──
        'wmi', 'win32com', 'win32com.client', 'win32com.server',
        'pywintypes', 'win32api', 'win32con',
        # ── psutil ──
        'psutil', 'psutil._pswindows',
        # ── QR Code ──
        'qrcode', 'qrcode.image', 'qrcode.image.pil',
        'qrcode.constants', 'qrcode.exceptions', 'qrcode.main',
        # ── Pillow ──
        'PIL', 'PIL.Image', 'PIL.ImageDraw', 'PIL.ImageFont',
        # ── OpenCV ──
        'cv2',
        # ── NumPy ──
        'numpy',
        # ── Sounddevice ──
        'sounddevice',
        # ── Network / Web ──
        'requests', 'certifi', 'ssl',
        'bs4', 'bs4.builder', 'bs4.builder._htmlparser',
        # ── Playwright (optional — warranty lookup) ──
        'playwright', 'playwright.sync_api',
        # ── Local packages ──
        'controllers', 'controllers.scan_controller',
        'controllers.checklist_controller',
        'controllers.pricing_controller',
        'controllers.cam_mic_controller',
        'controllers.warranty_controller',
        'models', 'models.hardware', 'models.checklist', 'models.pricing',
        'views', 'views.wizard', 'views.sidebar',
        'views.hardware_tab', 'views.checklist_tab',
        'views.components', 'views.components.theme',
        'views.components.cam_mic_widget',
        'views.components.checklist_card',
        'views.components.grade_badge',
        'views.components.hw_info',
        'views.components.keyboard_test',
        'views.components.loading_spinner',
        'views.components.price_card',
        'views.components.qr_widget',
        'views.components.screen_test',
        'views.components.warranty_widget',
        'gemini_pricer', 'scanner',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib', 'scipy', 'pandas',
        'IPython', 'jupyter', 'notebook',
        'tkinter', 'test', 'unittest',
    ],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='O2O_Inspection',
    debug=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon='icon.ico',
)
