# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec — macOS .app bundle  (v2.0)
# Chạy: pyinstaller EasySwap_Inspection_mac.spec --clean --noconfirm

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('checklist.json', '.'),
    ],
    hiddenimports=[
        # ── API key (generated by build_inject_key.py) ──
        '_embedded_key',
        # ── psutil macOS ──
        'psutil', 'psutil._psmacosx', 'psutil._psposix', 'psutil._common',
        # ── QR Code ──
        'qrcode', 'qrcode.image', 'qrcode.image.pil',
        'qrcode.constants', 'qrcode.exceptions', 'qrcode.main',
        # ── Pillow ──
        'PIL', 'PIL.Image', 'PIL.ImageDraw', 'PIL.ImageFont',
        # ── OpenCV ──
        'cv2',
        # ── NumPy ──
        'numpy',
        # ── Sounddevice ──
        'sounddevice',
        # ── Network / Web ──
        'requests', 'certifi', 'ssl', 'plistlib',
        'bs4', 'bs4.builder', 'bs4.builder._htmlparser',
        # ── Playwright (optional — warranty lookup) ──
        'playwright', 'playwright.sync_api',
        # ── Local packages ──
        'controllers', 'controllers.scan_controller',
        'controllers.checklist_controller',
        'controllers.pricing_controller',
        'controllers.cam_mic_controller',
        'controllers.warranty_controller',
        'models', 'models.hardware', 'models.checklist', 'models.pricing',
        'views', 'views.wizard', 'views.sidebar',
        'views.hardware_tab', 'views.checklist_tab',
        'views.components', 'views.components.theme',
        'views.components.cam_mic_widget',
        'views.components.checklist_card',
        'views.components.grade_badge',
        'views.components.hw_info',
        'views.components.keyboard_test',
        'views.components.loading_spinner',
        'views.components.price_card',
        'views.components.qr_widget',
        'views.components.screen_test',
        'views.components.warranty_widget',
        'gemini_pricer', 'scanner',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'wmi', 'win32com', 'win32api', 'win32con', 'pywintypes',
        'matplotlib', 'scipy', 'pandas',
        'IPython', 'jupyter', 'notebook',
        'tkinter', 'test', 'unittest',
    ],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='EasySwap_Inspection',
    debug=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.icns',
)

app = BUNDLE(
    exe,
    name='EasySwap_Inspection.app',
    icon='icon.icns',
    bundle_identifier='com.easyswap.inspection',
    info_plist={
        'CFBundleName': 'Easy Swap',
        'CFBundleDisplayName': 'Easy Swap Inspection',
        'CFBundleVersion': '2.0.0',
        'CFBundleShortVersionString': '2.0.0',
        'NSHighResolutionCapable': True,
        'NSRequiresAquaSystemAppearance': False,
        'NSCameraUsageDescription': 'Kiểm tra camera laptop',
        'NSMicrophoneUsageDescription': 'Kiểm tra microphone laptop',
    },
)
